---
title: "Received"
output: 
  flexdashboard::flex_dashboard:
  vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE,warning = FALSE)
library(tidyverse)
library(lubridate)
library(DT)
source(file = "Data_Access/database_functions.R")
source(file = "Shared/datatable_JS.R")
```

```{r, echo=FALSE}
conn <- sql01_con("Coin")

LineMap <- tbl(conn,"ddfJobType") %>%
  select(JobPrefix, ProductLine) %>%
  mutate(JobPrefix = str_trim(JobPrefix)) %>% 
  filter(!is.na(ProductLine)) %>% 
  collect()

dayRange <- c(seq(day(today()), day(today()) - 7))
weekRange <- c(seq(isoweek(today()), isoweek(today()) - 4))
monthRange <- c(seq(month(today()), month(today()) -4))

vw <- sql01_query("Coin", 
    "select	Brand, OrderStatus, Plant, ReceivedDate, OrderCaseTotal,   
    ShopFloorNumber, OrderTotal
    from vwReportKeyData
    where datediff(month, ReceivedDate, getdate()) < 6 and OrderCaseTotal > 0 and OrderStatus <> 
    'Cancelled'
    ")

t <- vw %>%
  mutate(JobPrefix = str_sub(ShopFloorNumber, 1, 2)) %>%
  mutate(weekNo = isoweek(ReceivedDate)) %>% 
  mutate(dayNo = day(ReceivedDate)) %>% 
  mutate(monthNo = month(ReceivedDate))
```

```{r, echo=FALSE}
  
daily <- inner_join(t,LineMap,by="JobPrefix") %>% 
  select(dayNo, ReceivedDate, OrderCaseTotal,OrderTotal, Brand, ProductLine) %>%
  filter(ReceivedDate > (today() - 6)) %>%   
  filter(ProductLine %in% c("Framed", "Full Access")) %>% 
  group_by(dayNo, Brand, ProductLine) %>% 
  summarise(Cases = sum(OrderCaseTotal), Dollars = sum(OrderTotal)) %>%
  ungroup()
  
#if missing productline 
# daily2 <- 

weekly <- inner_join(t,LineMap,by="JobPrefix") %>% 
  select(weekNo, OrderCaseTotal,OrderTotal, Brand, ProductLine) %>% 
  filter(weekNo %in% weekRange) %>%
  filter(ProductLine %in% c("Framed", "Full Access")) %>% 
  group_by(weekNo, Brand, ProductLine) %>% 
  summarise(Cases = sum(OrderCaseTotal), Dollars = sum(OrderTotal)) %>%
  ungroup() 

monthly <- inner_join(t,LineMap,by="JobPrefix") %>% 
  select(monthNo, OrderCaseTotal,OrderTotal, Brand, ProductLine) %>% 
  filter(monthNo %in% monthRange) %>%
  filter(ProductLine %in% c("Framed", "Full Access")) %>% 
  group_by(monthNo, Brand, ProductLine) %>% 
  summarise(Cases = sum(OrderCaseTotal), Dollars = sum(OrderTotal)) %>%
  ungroup() 

daily_tbl <- daily %>% 
  pivot_wider(names_from = c("Brand", "ProductLine"), values_from = c("Cases", "Dollars")) %>% 
  mutate_if(is.numeric, coalesce, ... = 0) %>% 
  mutate(total_cases = Cases_Greenfield_Framed + `Cases_Greenfield_Full Access` + `Cases_Siteline_Full Access`) %>% 
  mutate(total_dollars = Dollars_Greenfield_Framed + `Dollars_Greenfield_Full Access` + `Dollars_Siteline_Full Access`) %>% 
  mutate(total_avg_case = (Dollars_Greenfield_Framed + `Dollars_Greenfield_Full Access` + `Dollars_Siteline_Full Access`) / (Cases_Greenfield_Framed + `Cases_Greenfield_Full Access` + `Cases_Siteline_Full Access`))

weekly_tbl <- weekly %>% 
  pivot_wider(names_from = c("Brand", "ProductLine"), values_from = c("Cases", "Dollars"))  %>% 
  mutate_if(is.numeric, coalesce, ... = 0) %>% 
  mutate(total_cases = Cases_Greenfield_Framed + `Cases_Greenfield_Full Access` + `Cases_Siteline_Full Access`) %>% 
  mutate(total_dollars = Dollars_Greenfield_Framed + `Dollars_Greenfield_Full Access` + `Dollars_Siteline_Full Access`) %>% 
  mutate(total_avg_case = (Dollars_Greenfield_Framed + `Dollars_Greenfield_Full Access` + `Dollars_Siteline_Full Access`) / (Cases_Greenfield_Framed + `Cases_Greenfield_Full Access` + `Cases_Siteline_Full Access`))


monthly_tbl <- monthly %>% 
  pivot_wider(names_from = c("Brand", "ProductLine"), values_from = c("Cases", "Dollars"))  %>% 
  mutate_if(is.numeric, coalesce, ... = 0) %>% 
  mutate(total_cases = Cases_Greenfield_Framed + `Cases_Greenfield_Full Access` + `Cases_Siteline_Full Access`) %>% 
  mutate(total_dollars = Dollars_Greenfield_Framed + `Dollars_Greenfield_Full Access` + `Dollars_Siteline_Full Access`) %>% 
  mutate(total_avg_case = (Dollars_Greenfield_Framed + `Dollars_Greenfield_Full Access` + `Dollars_Siteline_Full Access`) / (Cases_Greenfield_Framed + `Cases_Greenfield_Full Access` + `Cases_Siteline_Full Access`))


daily_dt <- daily_tbl %>% 
  transmute( 
      'Day' = dayNo,
      'Greenfield Framed' = Cases_Greenfield_Framed,
      'Greenfield Framed $' = Dollars_Greenfield_Framed,
      'Greenfield Framed Avg/Case' =Dollars_Greenfield_Framed / Cases_Greenfield_Framed,
      'Greenfield Full Access' = `Cases_Greenfield_Full Access`,
      'Greenfild Full Access $' = `Dollars_Greenfield_Full Access`,
      'Greenfield Full Access Avg/Case' = `Dollars_Greenfield_Full Access` / `Cases_Greenfield_Full Access`,
      'Siteline Full Access' = `Cases_Siteline_Full Access`,
      'Siteline Full Access $' = `Dollars_Siteline_Full Access`,
      'Siteline Full Access Avg/Case' = `Dollars_Siteline_Full Access` / `Cases_Siteline_Full Access`,
      'Total Cases' = total_cases,
      'Total $' = total_dollars,
      'Total Avg/Case' = total_avg_case
  ) %>% 
  mutate_if(is.numeric, coalesce, ... = 0)
  

weekly_dt <- weekly_tbl %>% 
  transmute( 
      'Week#' = weekNo,
      'Greenfield Framed' = Cases_Greenfield_Framed,
      'Greenfield Framed $' = Dollars_Greenfield_Framed,
      'Greenfield Framed Avg/Case' =Dollars_Greenfield_Framed / Cases_Greenfield_Framed,
      'Greenfield Full Access' = `Cases_Greenfield_Full Access`,
      'Greenfild Full Access $' = `Dollars_Greenfield_Full Access`,
      'Greenfield Full Access Avg/Case' = `Dollars_Greenfield_Full Access` / `Cases_Greenfield_Full Access`,
      'Siteline Full Access' = `Cases_Siteline_Full Access`,
      'Siteline Full Access $' = `Dollars_Siteline_Full Access`,
      'Siteline Full Access Avg/Case' = `Dollars_Siteline_Full Access` / `Cases_Siteline_Full Access`,
      'Total Cases' = total_cases,
      'Total $' = total_dollars,
      'Total Avg/Case' = total_avg_case
  ) %>% 
  mutate_if(is.numeric, coalesce, ... = 0)
  
monthly_dt <- monthly_tbl %>% 
  transmute( 
      'Month' = monthNo,
      'Greenfield Framed' = Cases_Greenfield_Framed,
      'Greenfield Framed $' = Dollars_Greenfield_Framed,
      'Greenfield Framed Avg/Case' =Dollars_Greenfield_Framed / Cases_Greenfield_Framed,
      'Greenfield Full Access' = `Cases_Greenfield_Full Access`,
      'Greenfild Full Access $' = `Dollars_Greenfield_Full Access`,
      'Greenfield Full Access Avg/Case' = `Dollars_Greenfield_Full Access` / `Cases_Greenfield_Full Access`,
      'Siteline Full Access' = `Cases_Siteline_Full Access`,
      'Siteline Full Access $' = `Dollars_Siteline_Full Access`,
      'Siteline Full Access Avg/Case' = `Dollars_Siteline_Full Access` / `Cases_Siteline_Full Access`,
      'Total Cases' = total_cases,
      'Total $' = total_dollars,
      'Total Avg/Case' = total_avg_case
  ) %>% 
  mutate_if(is.numeric, coalesce, ... = 0)

```



Daily 
===================================== 

### Daily

```{r, echo=FALSE}
javascript <- JS(
  js_op_aux("start"),
  # js_op(1, operation = "count", txt = "Contador: "),
  js_op(0, operation = "custom", txt = "Total: "),
  js_op(1, operation = "sum"),
  js_op(2, format = "currency",operation = "sum", signif = 0),
  # js_op(3, format = "currency", operation = "mean", signif = 0),
  js_op(4, operation = "sum"),
  js_op(5, format = "currency", operation = "sum", signif = 0),
  # js_op(6, format = "currency", operation = "mean", signif = 0),
  js_op(7, operation = "sum"),
  js_op(8, format = "currency", operation = "sum", signif = 0),
  # js_op(9, format = "currency", operation = "mean", signif = 0),
  js_op(10, operation = "sum"),
  js_op(11, format = "currency", operation = "sum", signif = 0),
  js_op(12, format = "currency", operation = "mean", signif = 0),
  js_op_aux("end")
  )


ddt <- datatable(daily_dt, container = js_op_aux("sketch", daily_dt), options = list(paging = FALSE, 
  searching = FALSE, footerCallback = javascript), rownames = FALSE) %>% 
  formatCurrency(c(3:4,6:7,9:10,12:13), digits = 0) 
renderDataTable(ddt)

```

Weekly
===================================== 
### Weekly 

```{r, echo=FALSE}
dt <- datatable(weekly_dt, container = js_op_aux("sketch", weekly_dt), options = list(paging = FALSE, searching = FALSE, footerCallback = javascript), rownames = FALSE) %>% 
  formatCurrency(c(3:4,6:7,9:10,12:13), digits = 0) 
renderDataTable(dt)
```

Monthly
===================================== 
### Monthly

```{r, echo=FALSE}
mdt <- datatable(monthly_dt, container = js_op_aux("sketch", monthly_dt), options = list(paging = FALSE, searching = FALSE, footerCallback = javascript), rownames = FALSE) %>% 
  formatCurrency(c(3:4,6:7,9:10,12:13), digits = 0) 
renderDataTable(mdt)

```
